version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AWSSDK.Core
    versions:
    - 3.5.2.3
    - 3.5.2.6
    - 3.5.2.8
    - 3.5.3
    - 3.5.3.2
    - 3.5.3.3
    - 3.5.3.5
    - 3.5.3.6
    - 3.5.3.7
    - 3.5.3.8
    - 3.7.0.10
    - 3.7.0.13
    - 3.7.0.14
    - 3.7.0.15
    - 3.7.0.3
    - 3.7.0.4
    - 3.7.0.7
  - dependency-name: AWSSDK.S3
    versions:
    - 3.5.10
    - 3.5.10.1
    - 3.5.7.11
    - 3.5.8.1
    - 3.5.8.3
    - 3.5.8.8
    - 3.5.9
    - 3.5.9.1
    - 3.5.9.3
    - 3.5.9.4
    - 3.5.9.5
    - 3.5.9.6
    - 3.5.9.7
    - 3.5.9.8
    - 3.7.0.10
    - 3.7.0.12
    - 3.7.0.14
    - 3.7.0.15
    - 3.7.0.16
    - 3.7.0.2
    - 3.7.0.3
    - 3.7.0.4
    - 3.7.0.7
  - dependency-name: Magick.NET-Q16-x64
    versions:
    - 7.23.2.1
    - 7.23.3
    - 7.23.4
  - dependency-name: Microting.eForm
    versions:
    - 4.3.17
    - 4.3.18
    - 4.4.19
    - 4.4.22
    - 4.4.7
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.111
    - 2.0.112
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.4
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Identity.UI
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Authentication.JwtBearer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Tools
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.InMemory
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Swashbuckle.AspNetCore
    versions:
    - 6.0.5
  - dependency-name: AWSSDK.SQS
    versions:
    - 3.5.1.13
    - 3.5.1.15
    - 3.5.1.16
    - 3.5.1.17
    - 3.5.1.19
  - dependency-name: NUnit
    versions:
    - 3.13.1
- package-ecosystem: npm
  directory: "/eform-client"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.35
    - 15.0.0
    - 15.0.1
  - dependency-name: "@wdio/spec-reporter"
    versions:
    - 7.0.7
    - 7.2.0
    - 7.5.2
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: "@wdio/mocha-framework"
    versions:
    - 7.4.6
  - dependency-name: webdriverio
    versions:
    - 7.0.5
    - 7.2.0
    - 7.2.1
    - 7.4.2
  - dependency-name: date-fns
    versions:
    - 2.20.3
  - dependency-name: "@wdio/local-runner"
    versions:
    - 7.0.0
    - 7.2.0
    - 7.2.1
    - 7.2.2
    - 7.4.2
  - dependency-name: "@wdio/cli"
    versions:
    - 7.1.0
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.4.2
  - dependency-name: "@wdio/sync"
    versions:
    - 7.0.5
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.3.0
    - 7.4.2
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.5
  - dependency-name: chai
    versions:
    - 4.3.1
    - 4.3.4
  - dependency-name: "@circlon/angular-tree-component"
    versions:
    - 10.0.2
    - 11.0.0
  - dependency-name: "@ng-select/ng-select"
    versions:
    - 6.0.0
  - dependency-name: "@fortawesome/angular-fontawesome"
    versions:
    - 0.8.2
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
  - dependency-name: fibers
    versions:
    - 5.0.0
  - dependency-name: ngx-cookie-service
    versions:
    - 11.0.2
