dist: trusty
sudo: false
language: csharp
mono: none
dotnet: 1.0.3
install: 
- nvm install 8.0.0
- nvm use 8.0.0
script:
- travis_retry dotnet restore ./eFormAPI/eFormAPI.sln
- cd eform-client && npm install && npm test
after_success:
- echo dotnet test and npm test succeeded
after_faliure:
- echo dotnet test and npm test failed