dist: xenial
language: csharp
mono: none
dotnet: 2.2
services:
- mysql
script:
  - rabbitmqctl add_user admin password 
  - rabbitmqctl set_user_tags admin administrator
  - rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
  - wget http://localhost:15672/cli/rabbitmqadmin
  - chmod +x rabbitmqadmin
  - ./rabbitmqadmin declare queue name=eformsdk-input durable=true
  - dotnet restore -v q eFormAPI/eFormAPI.sln
  - dotnet build eFormAPI/eFormAPI.sln
  - dotnet test -v n eFormAPI/eFormAPI.Web.Tests/eFormAPI.Web.Tests.csproj
  - dotnet test -v n eFormAPI/eFormAPI.Web.Integration.Tests/eFormAPI.Web.Integration.Tests.csproj
  - cd eform-client && npm install
  - npm start &
  - sleep 40
  - dotnet run --project ../eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj > dotnet_log 2>&1 &
  - sleep 40
  - npm run testheadless
  - sleep 40
  - dotnet run --project ../eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj > dotnet_log 2>&1 &
  - sleep 40
  - npm run testheadless2
after_success:
- echo dotnet test and npm test succeeded
after_faliure:
- echo dotnet test and npm test failed
