dist: trusty
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
sudo: required
language: csharp
mono: latest
dotnet: 2.0.0
install: 
- nvm install 8.0.0
- nvm use 8.0.0
script:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./eFormAPI/eFormAPI.sln
- xbuild ./eFormAPI/eFormAPI.sln
- cd eform-client && npm install && npm test
after_success:
- echo dotnet test and npm test succeeded
after_faliure:
- echo dotnet test and npm test failed