dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
sudo: required
language: csharp
mono: none
dotnet: 2.1
bundler_args: --retry 5
install: 
- nvm install 8.0.0
- nvm use 8.0.0
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- fluxbox > /dev/null 2>&1 &
script:
script:
  - cd eFormAPI && dotnet restore
  - cd eFormAPI && dotnet build eFormAPI/eFormAPI.sln
  - cd eFormAPI && dotnet test -v n eFormAPI/eFormAPI.Web.Tests/eFormAPI.Web.Tests.csproj
  - cd eFormAPI && dotnet test -v n eFormAPI/eFormAPI.Web.Integration.Tests/eFormAPI.Web.Integration.Tests.csproj
  - cd eform-client && npm install
after_success:
- echo dotnet test and npm test succeeded
after_faliure:
- echo dotnet test and npm test failed