language: csharp
mono: none
dotnet: 1.0.3
dist: trusty
solution: "./eFormAPI/eFormAPI.sln"
install:
- travis_retry dotnet restore ./eFormAPI/eFormAPI.sln
script:
- dotnet restore
- xbuild ./eFormAPI/eFormAPI.sln