dist: trusty
addons:
  firefox: latest
  chrome: stable
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
sudo: required
language: csharp
mono: none
dotnet: 2.1
bundler_args: --retry 5
before_install:
  - google-chrome-stable --headless --disable-gpu
install:
- nvm install 8.0.0
- nvm use 8.0.0
- npm install
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- fluxbox > /dev/null 2>&1 &
script:
  - dotnet restore -v q eFormAPI/eFormAPI.sln
  - dotnet build eFormAPI/eFormAPI.sln
  - dotnet test -v n eFormAPI/eFormAPI.Web.Tests/eFormAPI.Web.Tests.csproj
  - dotnet test -v n eFormAPI/eFormAPI.Web.Integration.Tests/eFormAPI.Web.Integration.Tests.csproj
  - cd eform-client && npm install
  - dotnet run --project ../eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj &
  - npm run testheadless
  - dotnet run --project ../eFormAPI/eFormAPI.Web/eFormAPI.Web.csproj &
  - npm run testheadless2
after_success:
- echo dotnet test and npm test succeeded
after_faliure:
- echo dotnet test and npm test failed