version: '3.4'
services:
  angular:
    image: microtingas/angular-frontend:latest
    depends_on:
      - mariadb
      - rabbitmq
    networks:
      - frontend
      - backend
    ports:
      - '80:5000'
    restart: on-failure
    volumes:
      - ${PWD}/mybb:/var/www/html

  mariadb:
    image: mariadb:10.4.10
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MARIADB_ROOT_PASSWORD: secretpassword
      MARIADB_USER: tester
      MARIADB_PASSWORD: secretpassword
    networks:
      - backend
    restart: on-failure
    volumes:
     - ${PWD}/mariadb104:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.6.15-management
    container_name: rabbitmq
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/logs/:/var/log/rabbitmq/
    networks:
      - backend
    ports:
        - 5672:5672
        - 15672:15672

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
