apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "my-first-cron"
  labels: {{- include "angularfrontend.labels" . | nindent 4 }}
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: "{{ .Values.cronjob.repository }}:{{ .Values.cronjob.image.tag }}"
            name: "my-first-cron"
            command: ['sh', '/perform-backup.sh']
            args:
              [
                'AWS_SECRET_ACCESS_KEY="hej"',
                'AWS_BUCKET_BACKUP_PATH="bla"',
                'AWS_BUCKET_NAME="blaer"',
                'NO_DB_NAME="true"',
                'MAX_NUMBER_OF_BACKUPS=290',
                'TARGET_DATABASE_HOST={{ include "angularfrontend.databaseHost" . }}',
                'TARGET_DATABASE_USER=root',
                'TARGET_DATABASE_PASSWORD=secretpassword',
                'TARGET_DATABASE_NAMES={{ regexReplaceAll "frontend-(x*)" .Release.Name "$1" }}_SDK'
              ]
            imagePullPolicy: Always
